// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmxfxpintfxtirwvvfwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteGZ4cGludGZ4dGlyd3Z2ZndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjc2NjAsImV4cCI6MjA3Mjk0MzY2MH0.F31CFe7kAihIydKix1P2C4ZwzewHPFPKUlybuvH4L3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});